# Generated by Django 3.1.7 on 2021-04-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderTime',
        ),
        migrations.AlterField(
            model_name='createevent',
            name='user_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='автор  события'),
        ),
    ]
