# Generated by Django 3.1.7 on 2021-07-15 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20210715_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='reminder',
            field=models.CharField(blank=True, choices=[(datetime.timedelta(seconds=3600), 'За час'), (datetime.timedelta(seconds=7200), 'За 2 часа'), (datetime.timedelta(seconds=14400), 'За 4 часа'), (datetime.timedelta(days=1), 'За день'), (datetime.timedelta(days=7), 'За неделю')], max_length=40, null=True, verbose_name='Когда напомнить?'),
        ),
    ]
