# Generated by Django 3.1.7 on 2021-08-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20210715_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.country'),
        ),
        migrations.AlterUniqueTogether(
            name='profileuser',
            unique_together=set(),
        ),
    ]
