# Generated by Django 3.2.6 on 2021-10-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20210826_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='cal.country'),
        ),
    ]
